-- Create Attendees Table
create table public.attendees (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  created_at timestamp with time zone default now(),
  unique(name, phone)
);

-- Create Attendance Logs Table
create table public.attendance_logs (
  id bigint generated by default as identity primary key,
  attendee_id uuid references public.attendees(id),
  name text not null,
  phone text not null,
  created_at timestamp with time zone default now()
);

-- Enable RLS (Recommended, though we use explicit server actions)
alter table public.attendees enable row level security;
alter table public.attendance_logs enable row level security;

-- Policies (Simple public access for demo, ideally stricter)
-- Allow anyone to insert attendee (User Registration)
create policy "Allow public insert attendees" on public.attendees for insert with check (true);
create policy "Allow public read attendees" on public.attendees for select using (true);

-- Allow anyone to insert logs (Scanned by admin, but technically anyone with key if insecure)
create policy "Allow public insert logs" on public.attendance_logs for insert with check (true);
create policy "Allow public read logs" on public.attendance_logs for select using (true);
create policy "Allow public delete logs" on public.attendance_logs for delete using (true);
