-- Create Growth Stats Table for 2026 Vision Dashboard
create table public.growth_stats (
  id bigint generated by default as identity primary key,
  attendee_id uuid references public.attendees(id) not null,
  quarter text not null, -- e.g., '2026-1Q'
  
  -- Metrics
  absent_count integer default 0,
  bible_score integer default 20, -- Default to perfect, deduct as needed
  prayer_score integer default 0,
  evangelism_count integer default 0,
  service_score integer default 7, -- Default 'Average'
  special_score integer default 7, -- Default 'Average'
  
  updated_at timestamp with time zone default now(),
  
  -- Ensure one record per user per quarter
  unique(attendee_id, quarter)
);

-- RLS Policies
alter table public.growth_stats enable row level security;

-- Allow public read (for users to see their own stats via server actions)
create policy "Allow public read growth_stats" on public.growth_stats for select using (true);

-- Allow public insert/update (guarded by business logic/admin check in app)
create policy "Allow public insert growth_stats" on public.growth_stats for insert with check (true);
create policy "Allow public update growth_stats" on public.growth_stats for update using (true);
create policy "Allow public delete growth_stats" on public.growth_stats for delete using (true);
