
-- Create Schedules Table (for 2026 Calendar)
create table public.schedules (
  id bigint generated by default as identity primary key,
  title text not null,
  date timestamp with time zone not null,
  type text default 'primary', -- primary (blue), success (green), danger (red), warning (yellow)
  created_at timestamp with time zone default now()
);

-- RLS Policies
alter table public.schedules enable row level security;

-- Allow public read
create policy "Allow public read schedules" on public.schedules for select using (true);

-- Allow admin write (public for now, guarded by app logic, or rely on key)
create policy "Allow public insert schedules" on public.schedules for insert with check (true);
create policy "Allow public delete schedules" on public.schedules for delete using (true);
